### PR TITLE
utf8 table, postgresql style

### PR DESCRIPTION
**Pull request by paranormal**
What do you think?

### CODE REVIEW

**Comment by paranormal** [comment]
I'm not sure about colours, I'd seen something like this a long time ago.
I mean initialization, then bunch of stuff, then just \e[0m... Is it ok?

**Comment by chokepoint** [comment]
Can you tuck that away in a print_banner() function? That'll keep main less cluttered, then I'll merge it in

**Comment by paranormal** [comment]
Ok, I will.

**Comment by paranormal** [comment]
Done.

**Comment by chokepoint** [comment]
Merged. I was out for a few days. Thanks for the update

**Pull request merged**
